// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: order.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for OrderSrv service

type OrderSrvService interface {
	// 获取一个订单的信息
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...client.CallOption) (*Order, error)
}

type orderSrvService struct {
	c    client.Client
	name string
}

func NewOrderSrvService(name string, c client.Client) OrderSrvService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "proto"
	}
	return &orderSrvService{
		c:    c,
		name: name,
	}
}

func (c *orderSrvService) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...client.CallOption) (*Order, error) {
	req := c.c.NewRequest(c.name, "OrderSrv.GetOrder", in)
	out := new(Order)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OrderSrv service

type OrderSrvHandler interface {
	// 获取一个订单的信息
	GetOrder(context.Context, *GetOrderRequest, *Order) error
}

func RegisterOrderSrvHandler(s server.Server, hdlr OrderSrvHandler, opts ...server.HandlerOption) error {
	type orderSrv interface {
		GetOrder(ctx context.Context, in *GetOrderRequest, out *Order) error
	}
	type OrderSrv struct {
		orderSrv
	}
	h := &orderSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&OrderSrv{h}, opts...))
}

type orderSrvHandler struct {
	OrderSrvHandler
}

func (h *orderSrvHandler) GetOrder(ctx context.Context, in *GetOrderRequest, out *Order) error {
	return h.OrderSrvHandler.GetOrder(ctx, in, out)
}
