// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 获取订单的请求信息
type GetOrderRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 定义订单消息
type Order struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	CreateTime           string   `protobuf:"bytes,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Order) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Order) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Order) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Order) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetOrderRequest)(nil), "proto.GetOrderRequest")
	proto.RegisterType((*Order)(nil), "proto.Order")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0x4e, 0x85, 0x30,
	0x10, 0x45, 0x2d, 0xbe, 0x3e, 0x70, 0x34, 0x9a, 0x4c, 0x8c, 0x69, 0x58, 0x18, 0x64, 0xc5, 0x8a,
	0x05, 0xee, 0xdd, 0xba, 0x34, 0xa9, 0xfe, 0x00, 0xd2, 0x49, 0xec, 0x02, 0x8a, 0xd3, 0xe2, 0x5f,
	0xf9, 0x8f, 0xc6, 0x41, 0xcc, 0x0b, 0xab, 0xf6, 0xdc, 0x73, 0xd3, 0xf4, 0xc2, 0x65, 0x60, 0x47,
	0xdc, 0xce, 0x1c, 0x52, 0x40, 0x2d, 0x47, 0xfd, 0x00, 0x37, 0xcf, 0x94, 0x5e, 0x7e, 0x85, 0xa5,
	0xcf, 0x85, 0x62, 0xc2, 0x6b, 0xc8, 0xbc, 0x33, 0xaa, 0x52, 0x8d, 0xb6, 0x99, 0x77, 0xf5, 0xb7,
	0x02, 0x2d, 0x85, 0xbd, 0x41, 0x84, 0xc3, 0xd4, 0x8f, 0x64, 0xb2, 0x4a, 0x35, 0x17, 0x56, 0xee,
	0x78, 0x0b, 0x7a, 0x66, 0x3f, 0x90, 0x39, 0xaf, 0x54, 0xa3, 0xec, 0x0a, 0x58, 0x42, 0xb1, 0x44,
	0x62, 0x69, 0x1f, 0xa4, 0xfd, 0xcf, 0x68, 0x20, 0xef, 0x9d, 0x63, 0x8a, 0xd1, 0x68, 0x51, 0x1b,
	0xca, 0x5b, 0x1f, 0x61, 0x22, 0x73, 0x94, 0x7c, 0x05, 0xbc, 0x07, 0x18, 0x98, 0xfa, 0x44, 0x6f,
	0x7e, 0x24, 0x93, 0x8b, 0x3a, 0x49, 0xba, 0x27, 0x28, 0xe4, 0xbb, 0xaf, 0xfc, 0x85, 0x1d, 0x14,
	0xdb, 0x3c, 0xbc, 0x5b, 0x97, 0xb7, 0xbb, 0xbd, 0xe5, 0xd5, 0x5f, 0x2e, 0x61, 0x7d, 0xf6, 0x7e,
	0x14, 0x7c, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x13, 0x43, 0xb0, 0x36, 0x2f, 0x01, 0x00, 0x00,
}
